image: gitpod/workspace-full

tasks:
  - name: Download go modules
    init: go mod download
  - name: Install dependencies
    init: |
      go install github.com/bufbuild/buf/cmd/buf@v1.9.0

vscode:
  extensions:
    - golang.go
    - zxh404.vscode-proto3
